// SPDX-FileCopyrightText: (c) 2018 Daniel Czerwonk
//
// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Result struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Result) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AddRouteRequest struct {
	Route                *Route            `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	Communities          []*Community      `protobuf:"bytes,2,rep,name=communities,proto3" json:"communities,omitempty"`
	LargeCommunities     []*LargeCommunity `protobuf:"bytes,3,rep,name=large_communities,json=largeCommunities,proto3" json:"large_communities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AddRouteRequest) Reset()         { *m = AddRouteRequest{} }
func (m *AddRouteRequest) String() string { return proto.CompactTextString(m) }
func (*AddRouteRequest) ProtoMessage()    {}
func (*AddRouteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *AddRouteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRouteRequest.Unmarshal(m, b)
}
func (m *AddRouteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRouteRequest.Marshal(b, m, deterministic)
}
func (m *AddRouteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRouteRequest.Merge(m, src)
}
func (m *AddRouteRequest) XXX_Size() int {
	return xxx_messageInfo_AddRouteRequest.Size(m)
}
func (m *AddRouteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRouteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRouteRequest proto.InternalMessageInfo

func (m *AddRouteRequest) GetRoute() *Route {
	if m != nil {
		return m.Route
	}
	return nil
}

func (m *AddRouteRequest) GetCommunities() []*Community {
	if m != nil {
		return m.Communities
	}
	return nil
}

func (m *AddRouteRequest) GetLargeCommunities() []*LargeCommunity {
	if m != nil {
		return m.LargeCommunities
	}
	return nil
}

type WithdrawRouteRequest struct {
	Route                *Route   `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawRouteRequest) Reset()         { *m = WithdrawRouteRequest{} }
func (m *WithdrawRouteRequest) String() string { return proto.CompactTextString(m) }
func (*WithdrawRouteRequest) ProtoMessage()    {}
func (*WithdrawRouteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *WithdrawRouteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawRouteRequest.Unmarshal(m, b)
}
func (m *WithdrawRouteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawRouteRequest.Marshal(b, m, deterministic)
}
func (m *WithdrawRouteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawRouteRequest.Merge(m, src)
}
func (m *WithdrawRouteRequest) XXX_Size() int {
	return xxx_messageInfo_WithdrawRouteRequest.Size(m)
}
func (m *WithdrawRouteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawRouteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawRouteRequest proto.InternalMessageInfo

func (m *WithdrawRouteRequest) GetRoute() *Route {
	if m != nil {
		return m.Route
	}
	return nil
}

type Route struct {
	Prefix               *Prefix  `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	NextHop              []byte   `protobuf:"bytes,2,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
	LocalPref            uint32   `protobuf:"varint,3,opt,name=local_pref,json=localPref,proto3" json:"local_pref,omitempty"`
	Med                  uint32   `protobuf:"varint,4,opt,name=med,proto3" json:"med,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}
func (*Route) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *Route) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route.Unmarshal(m, b)
}
func (m *Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route.Marshal(b, m, deterministic)
}
func (m *Route) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route.Merge(m, src)
}
func (m *Route) XXX_Size() int {
	return xxx_messageInfo_Route.Size(m)
}
func (m *Route) XXX_DiscardUnknown() {
	xxx_messageInfo_Route.DiscardUnknown(m)
}

var xxx_messageInfo_Route proto.InternalMessageInfo

func (m *Route) GetPrefix() *Prefix {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *Route) GetNextHop() []byte {
	if m != nil {
		return m.NextHop
	}
	return nil
}

func (m *Route) GetLocalPref() uint32 {
	if m != nil {
		return m.LocalPref
	}
	return 0
}

func (m *Route) GetMed() uint32 {
	if m != nil {
		return m.Med
	}
	return 0
}

type Prefix struct {
	Ip                   []byte   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Length               uint32   `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prefix) Reset()         { *m = Prefix{} }
func (m *Prefix) String() string { return proto.CompactTextString(m) }
func (*Prefix) ProtoMessage()    {}
func (*Prefix) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *Prefix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prefix.Unmarshal(m, b)
}
func (m *Prefix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prefix.Marshal(b, m, deterministic)
}
func (m *Prefix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prefix.Merge(m, src)
}
func (m *Prefix) XXX_Size() int {
	return xxx_messageInfo_Prefix.Size(m)
}
func (m *Prefix) XXX_DiscardUnknown() {
	xxx_messageInfo_Prefix.DiscardUnknown(m)
}

var xxx_messageInfo_Prefix proto.InternalMessageInfo

func (m *Prefix) GetIp() []byte {
	if m != nil {
		return m.Ip
	}
	return nil
}

func (m *Prefix) GetLength() uint32 {
	if m != nil {
		return m.Length
	}
	return 0
}

type Community struct {
	Asn                  uint32   `protobuf:"varint,1,opt,name=asn,proto3" json:"asn,omitempty"`
	Value                uint32   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Community) Reset()         { *m = Community{} }
func (m *Community) String() string { return proto.CompactTextString(m) }
func (*Community) ProtoMessage()    {}
func (*Community) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *Community) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Community.Unmarshal(m, b)
}
func (m *Community) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Community.Marshal(b, m, deterministic)
}
func (m *Community) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Community.Merge(m, src)
}
func (m *Community) XXX_Size() int {
	return xxx_messageInfo_Community.Size(m)
}
func (m *Community) XXX_DiscardUnknown() {
	xxx_messageInfo_Community.DiscardUnknown(m)
}

var xxx_messageInfo_Community proto.InternalMessageInfo

func (m *Community) GetAsn() uint32 {
	if m != nil {
		return m.Asn
	}
	return 0
}

func (m *Community) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type LargeCommunity struct {
	GlobalAdministrator  uint32   `protobuf:"varint,1,opt,name=global_administrator,json=globalAdministrator,proto3" json:"global_administrator,omitempty"`
	LocalDataPart1       uint32   `protobuf:"varint,2,opt,name=local_data_part1,json=localDataPart1,proto3" json:"local_data_part1,omitempty"`
	LocalDataPart2       uint32   `protobuf:"varint,3,opt,name=local_data_part2,json=localDataPart2,proto3" json:"local_data_part2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LargeCommunity) Reset()         { *m = LargeCommunity{} }
func (m *LargeCommunity) String() string { return proto.CompactTextString(m) }
func (*LargeCommunity) ProtoMessage()    {}
func (*LargeCommunity) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *LargeCommunity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LargeCommunity.Unmarshal(m, b)
}
func (m *LargeCommunity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LargeCommunity.Marshal(b, m, deterministic)
}
func (m *LargeCommunity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LargeCommunity.Merge(m, src)
}
func (m *LargeCommunity) XXX_Size() int {
	return xxx_messageInfo_LargeCommunity.Size(m)
}
func (m *LargeCommunity) XXX_DiscardUnknown() {
	xxx_messageInfo_LargeCommunity.DiscardUnknown(m)
}

var xxx_messageInfo_LargeCommunity proto.InternalMessageInfo

func (m *LargeCommunity) GetGlobalAdministrator() uint32 {
	if m != nil {
		return m.GlobalAdministrator
	}
	return 0
}

func (m *LargeCommunity) GetLocalDataPart1() uint32 {
	if m != nil {
		return m.LocalDataPart1
	}
	return 0
}

func (m *LargeCommunity) GetLocalDataPart2() uint32 {
	if m != nil {
		return m.LocalDataPart2
	}
	return 0
}

func init() {
	proto.RegisterType((*Result)(nil), "Result")
	proto.RegisterType((*AddRouteRequest)(nil), "AddRouteRequest")
	proto.RegisterType((*WithdrawRouteRequest)(nil), "WithdrawRouteRequest")
	proto.RegisterType((*Route)(nil), "Route")
	proto.RegisterType((*Prefix)(nil), "Prefix")
	proto.RegisterType((*Community)(nil), "Community")
	proto.RegisterType((*LargeCommunity)(nil), "LargeCommunity")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 431 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xc5, 0x49, 0xe3, 0x34, 0x93, 0x26, 0x0d, 0x43, 0x40, 0x06, 0x81, 0x88, 0x7c, 0x21, 0x07,
	0x64, 0x11, 0x17, 0x71, 0xe2, 0x52, 0xe0, 0x80, 0x10, 0x87, 0x6a, 0x39, 0x70, 0xb4, 0xb6, 0xf6,
	0xe0, 0xac, 0xb4, 0xf6, 0x9a, 0xf5, 0xba, 0x94, 0x2f, 0xe1, 0xc0, 0xcf, 0xa2, 0x5d, 0x6f, 0xc1,
	0x41, 0x3d, 0xf4, 0x36, 0xef, 0xcd, 0xbc, 0x37, 0xbb, 0x33, 0x03, 0x33, 0xde, 0x88, 0xa4, 0xd1,
	0xca, 0xa8, 0xf8, 0x0d, 0x84, 0x8c, 0xda, 0x4e, 0x1a, 0x44, 0x38, 0xca, 0x55, 0x41, 0x51, 0xb0,
	0x09, 0xb6, 0x0b, 0xe6, 0x62, 0x8c, 0x60, 0x5a, 0x51, 0xdb, 0xf2, 0x92, 0xa2, 0xd1, 0x26, 0xd8,
	0xce, 0xd8, 0x0d, 0x8c, 0x7f, 0x07, 0x70, 0x7a, 0x5e, 0x14, 0x4c, 0x75, 0x86, 0x18, 0x7d, 0xef,
	0xa8, 0x35, 0xf8, 0x14, 0x26, 0xda, 0x62, 0x67, 0x31, 0x4f, 0xc3, 0xa4, 0xcf, 0xf6, 0x24, 0xbe,
	0x84, 0x79, 0xae, 0xaa, 0xaa, 0xab, 0x85, 0x11, 0xd4, 0x46, 0xa3, 0xcd, 0x78, 0x3b, 0x4f, 0x21,
	0x79, 0xef, 0xb9, 0x9f, 0x6c, 0x98, 0xc6, 0xb7, 0x70, 0x5f, 0x72, 0x5d, 0x52, 0x36, 0xd4, 0x8c,
	0x9d, 0xe6, 0x34, 0xf9, 0x6c, 0x33, 0xff, 0x84, 0x2b, 0x39, 0xc4, 0x82, 0xda, 0xf8, 0x35, 0xac,
	0xbf, 0x0a, 0xb3, 0x2f, 0x34, 0xff, 0x71, 0xf7, 0x17, 0xc6, 0x06, 0x26, 0x0e, 0xe3, 0x73, 0x08,
	0x1b, 0x4d, 0xdf, 0xc4, 0xb5, 0xaf, 0x9b, 0x26, 0x17, 0x0e, 0x32, 0x4f, 0xe3, 0x63, 0x38, 0xae,
	0xe9, 0xda, 0x64, 0x7b, 0xd5, 0xb8, 0xc1, 0x9c, 0xb0, 0xa9, 0xc5, 0x1f, 0x55, 0x83, 0xcf, 0x00,
	0xa4, 0xca, 0xb9, 0xcc, 0x6c, 0x69, 0x34, 0x76, 0xc3, 0x9c, 0x39, 0xc6, 0x7a, 0xe0, 0x0a, 0xc6,
	0x15, 0x15, 0xd1, 0x91, 0xe3, 0x6d, 0x18, 0xbf, 0x82, 0xb0, 0x77, 0xc7, 0x25, 0x8c, 0x44, 0xe3,
	0x5a, 0x9e, 0xb0, 0x91, 0x68, 0xf0, 0x11, 0x84, 0x92, 0xea, 0xd2, 0xec, 0x5d, 0x8f, 0x05, 0xf3,
	0x28, 0x3e, 0x83, 0xd9, 0xdf, 0xcf, 0x5b, 0x43, 0xde, 0xd6, 0x7e, 0x6b, 0x36, 0xc4, 0x35, 0x4c,
	0xae, 0xb8, 0xec, 0xc8, 0xab, 0x7a, 0x10, 0xff, 0x0a, 0x60, 0x79, 0x38, 0x37, 0xdc, 0xc1, 0xba,
	0x94, 0xea, 0x92, 0xcb, 0x8c, 0x17, 0x95, 0xa8, 0x45, 0x6b, 0x34, 0x37, 0x4a, 0x7b, 0xaf, 0x07,
	0x7d, 0xee, 0x7c, 0x98, 0xc2, 0x2d, 0xac, 0xfa, 0xdf, 0x15, 0xdc, 0xf0, 0xac, 0xe1, 0xda, 0xec,
	0x7c, 0x9b, 0xa5, 0xe3, 0x3f, 0x70, 0xc3, 0x2f, 0x2c, 0x7b, 0x4b, 0x65, 0xea, 0xa7, 0x71, 0x58,
	0x99, 0xa6, 0x12, 0x96, 0xef, 0x84, 0xfa, 0x44, 0xb9, 0xf9, 0x42, 0xfa, 0x4a, 0xe4, 0x84, 0x2f,
	0xe0, 0xf8, 0xe6, 0xb6, 0x70, 0x95, 0xfc, 0x77, 0x66, 0x4f, 0xa6, 0x49, 0x7f, 0xb1, 0xf1, 0x3d,
	0xdc, 0xc1, 0xe2, 0x60, 0xcf, 0xf8, 0x30, 0xb9, 0x6d, 0xef, 0x03, 0xc9, 0x65, 0xe8, 0xee, 0xfe,
	0xec, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0c, 0xa3, 0x65, 0x88, 0x04, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BioJectServiceClient is the client API for BioJectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BioJectServiceClient interface {
	AddRoute(ctx context.Context, in *AddRouteRequest, opts ...grpc.CallOption) (*Result, error)
	WithdrawRoute(ctx context.Context, in *WithdrawRouteRequest, opts ...grpc.CallOption) (*Result, error)
}

type bioJectServiceClient struct {
	cc *grpc.ClientConn
}

func NewBioJectServiceClient(cc *grpc.ClientConn) BioJectServiceClient {
	return &bioJectServiceClient{cc}
}

func (c *bioJectServiceClient) AddRoute(ctx context.Context, in *AddRouteRequest, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/BioJectService/AddRoute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bioJectServiceClient) WithdrawRoute(ctx context.Context, in *WithdrawRouteRequest, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/BioJectService/WithdrawRoute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BioJectServiceServer is the server API for BioJectService service.
type BioJectServiceServer interface {
	AddRoute(context.Context, *AddRouteRequest) (*Result, error)
	WithdrawRoute(context.Context, *WithdrawRouteRequest) (*Result, error)
}

// UnimplementedBioJectServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBioJectServiceServer struct {
}

func (*UnimplementedBioJectServiceServer) AddRoute(ctx context.Context, req *AddRouteRequest) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRoute not implemented")
}
func (*UnimplementedBioJectServiceServer) WithdrawRoute(ctx context.Context, req *WithdrawRouteRequest) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawRoute not implemented")
}

func RegisterBioJectServiceServer(s *grpc.Server, srv BioJectServiceServer) {
	s.RegisterService(&_BioJectService_serviceDesc, srv)
}

func _BioJectService_AddRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BioJectServiceServer).AddRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BioJectService/AddRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BioJectServiceServer).AddRoute(ctx, req.(*AddRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BioJectService_WithdrawRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BioJectServiceServer).WithdrawRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BioJectService/WithdrawRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BioJectServiceServer).WithdrawRoute(ctx, req.(*WithdrawRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BioJectService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "BioJectService",
	HandlerType: (*BioJectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddRoute",
			Handler:    _BioJectService_AddRoute_Handler,
		},
		{
			MethodName: "WithdrawRoute",
			Handler:    _BioJectService_WithdrawRoute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
