on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.23.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build server
      run: go build
      working-directory: cmd/bioject
    - name: Build client
      run: go build
      working-directory: cmd/biojecter
    - name: Run tests
      run: go test ./... -v -covermode=count
